#!/usr/bin/env node
/**
 * extract-slides.js
 * Run ONCE after cloning: node extract-slides.js path/to/liberty_gerador_v2.html
 * Extracts buildSlides() and buildS5() from the generator into _buildSlides.js
 */

const fs = require('fs')
const path = require('path')

const htmlPath = process.argv[2]
if (!htmlPath) {
  console.error('Usage: node extract-slides.js path/to/liberty_gerador_v2.html')
  process.exit(1)
}

const html = fs.readFileSync(htmlPath, 'utf8')

// Extract buildSlides
const bsIdx = html.indexOf('function buildSlides(')
const s5Idx = html.indexOf('\nfunction buildS5(')
const enrichIdx = html.indexOf('\nasync function enrichWithAI')

if (bsIdx === -1 || s5Idx === -1) {
  console.error('❌ buildSlides or buildS5 not found in HTML')
  process.exit(1)
}

let buildSlidesFn = html.slice(bsIdx, s5Idx)
let buildS5Fn     = html.slice(s5Idx + 1, enrichIdx)

// Fix buildSlides signature to accept external slides array
buildSlidesFn = buildSlidesFn.replace(
  'function buildSlides(d){\n  const slides=[];',
  'function buildSlides(d, slides=[]){' 
)

const output = [
  '// Auto-generated by extract-slides.js — do not edit manually',
  '// Regenerate: node extract-slides.js path/to/liberty_gerador_v2.html',
  '',
  'export ' + buildSlidesFn,
  '',
  'export ' + buildS5Fn,
].join('\n')

const outPath = path.join(__dirname, 'src/lib/_buildSlides.js')
fs.writeFileSync(outPath, output)
console.log(`✓ Extracted to ${outPath}`)
console.log(`  buildSlides: ${buildSlidesFn.length.toLocaleString()} chars`)
console.log(`  buildS5:     ${buildS5Fn.length.toLocaleString()} chars`)
